### ISSUE TITLE
GCE testing

### ISSUE THREAD

**Issue by Ba28** [kellrott/galaxy-tooldev-docs#15]
A few issues.  There was a spelling mistake in the instructions around #4.  "You can also to use for" should be "You can also use".

It wasn't clear at first that I had to make a project on the console first before trying to access the planemo image.  You should also mention that after creating a project, it is assigned an ID which you will use for the console.  

After figuring this out, I tried to access the planemo image but I got an error: 

ERROR: (gcloud.compute.images.create) Some requests did not succeed:
- Required 'read' permission for 'http://storage.googleapis.com/galaxyproject_images/planemo_machine.image.tar.gz'

You don't specify how to resolve this issue.  But even with the error, for some reason, when I access the site again and create a new disk, the planemo image appears...

**Comment by dannon** [comment]
Thanks for the grammatical fixes.  Regarding the image working all of a sudden -- I fixed it on our end when I saw #14 come in.

**Comment by kellrott** [comment]
Thank you for the report. 

It would be helpful if we could start to break up each of the issues into single subject threads, each with subject names that reflect the topic. This issue could be broken into multiple issues with names like:
1) Grammar mistake on Instruction 4 for GCE page
2) Need more instructions on how to initially create a GCE project
3) Read permission error during Planemo image loading

That we'd be able to address each of the concerns. And close each of the issues independently.

Also, try to merge issues into single topic threads. So, instead of creating a new issue, you could comment on #14 and say 'That happened to me to!'

**Comment by kellrott** [comment]
I think all of these issues have been taken care of
