### ISSUE TITLE
general testing comments - knowledge of Docker, testing example 

### ISSUE THREAD

**Issue by canghel** [kellrott/galaxy-tooldev-docs#3]
Hi there,

I installed Docker and Planemo, but with the help of our software developer (Chris Cooper).  I don't think I would have been able to do it without him (at least not without a lot of time puzzling through the documentation), and his main comment was that you needed a good knowedge of Docker to be able to go through the instructions.  (A more specific point he told me to mention is that we also had to install the python module "setuptools".)  So at the moment I'm able to do "sudo docker run -v `pwd`:/opt/galaxy/tools -v /var/run/docker.sock:/var/run/docker.sock -p 8010:80 -e GALAXY_DOCKER_ENABLED=true -e GALAXY_DOCKER_SUDO=true -e GALAXY_DOCKER_VOLUMES_FROM=planemo --name planemo planemo/box", then open another terminal to do "sudo docker exec -i -t planemo /bin/bash", and see the smc_het_example in my "/opt/galaxy/tools" folder. 

Ever Chris had some trouble on how to run the example.  This is the point where we stopped on Friday.  It might be useful to give more detailed step-by-step instructions to walk through the DPC example in particular?  

Thanks,
Catalina

**Comment by ChrisCooper** [comment]
Just to add to/clarify this a bit, the way I think they could be more specific is to state which commands should be run inside docker vs. outside (not obvious to people unfamiliar with VMs).  Since there are multiple way to set up development, I'm not sure what's the best way to lay out the instructions (seperate docs for each method, or just lots of little notes). The other potentially confusing part was the naming/taging of containers (I think this is the right term... I'm not a docker expert!). In the planemo docs, they use "-t planemo/box"

There are also references to the "tool directory" in a few places, but I don't think that concept is in the introduction or in the glossary. Even if it's just as simple as changing it to "the directory where you want to build your tools", it would make me feel less out of the loop. :)

Introdcution also has a hanging sentence:

```
Obtain a command line inside the
```

Also in the introduction, there is a command listed to "Deploy SDK". I think a deeper one or two sentence description of this would benefit non-docker users. Since this command never terminates, people might wait, expecting something to finish like all the previous setup commands do. Maybe something like "This starts the SDK running so you can access it in your browser, and you will need another terminal session if you want to run other commands. It won't stop until you press control-C".

**Comment by kellrott** [comment]
I'll start working through these comments. 
I'm thinking the Docker based instructions are for advanced users, and will mark them as such (there is also an issue request related to this issue at https://github.com/galaxyproject/planemo-machine/issues/26).
I've added new instructions related to deploying on GCE, which will be considered the easiest and most recommended path.

**Comment by kellrott** [comment]
The docker instructions have all been removed. I think we can close this issue. 
Are there any objections?
