### ISSUE TITLE
GCE testing 

### ISSUE THREAD

**Issue by NancyYuOICR** [kellrott/galaxy-tooldev-docs#7]
Some issues I faced: 
Creating a new instance:
- Boot Source: the picture shown in the instructions had "New Persistent Disk from Image".  On my computer, there was no option that states "New Persistent Disk from image".  Not sure if this important at all or what it's used for but this might confuse some users. 
- In my Networking: External IP: I wasn't sure what to choose for this: I couldn't see instructions for this.

Mount and format the disk: 
- "From the Google Compute instance, run the following command"  Might want to tell users where to run this from (include some intermediate steps -- maybe useful to direct users to SSH button)
- Step 3 didn't work for me.  Also may want to specify what chmod/chown does for users

**Comment by NancyYuOICR** [comment]
The errors it gave me when I ran step 3 in Mount and format the disk was:
grep: /etc/redhat-release: No such file or directory

**Comment by kellrott** [comment]
I'm a little confused about the first set of issues. Are you referring to instructions found in the google GCE manuals? I don't think our instructions have any pictures about "New Persistent Disk from Image"

For the second set of issues, I've tried to clean up instructions so that the SSH paragraph is more visible after the machine boot ( https://www.synapse.org/#!Synapse:syn2786217/wiki/209793 ). Is the a little clearer?
